// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4cM8f7lYGU7-ilIlC_QL6WXWvGgEqGrQ',
    appId: '1:696594231265:web:1ff8a23589b255b246eca0',
    messagingSenderId: '696594231265',
    projectId: 'leakdetectionapp',
    authDomain: 'leakdetectionapp.firebaseapp.com',
    storageBucket: 'leakdetectionapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3alHWr_3z961w6guU5yDIuJ4eEP_Mpc4',
    appId: '1:696594231265:android:3e6610db3f0f49c146eca0',
    messagingSenderId: '696594231265',
    projectId: 'leakdetectionapp',
    storageBucket: 'leakdetectionapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD0gp7p4YGjQYS1OuQtOaB7zS_KysLVeM',
    appId: '1:696594231265:ios:440b6dd5bf068b2e46eca0',
    messagingSenderId: '696594231265',
    projectId: 'leakdetectionapp',
    storageBucket: 'leakdetectionapp.firebasestorage.app',
    iosBundleId: 'com.example.leakdetectionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD0gp7p4YGjQYS1OuQtOaB7zS_KysLVeM',
    appId: '1:696594231265:ios:440b6dd5bf068b2e46eca0',
    messagingSenderId: '696594231265',
    projectId: 'leakdetectionapp',
    storageBucket: 'leakdetectionapp.firebasestorage.app',
    iosBundleId: 'com.example.leakdetectionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4cM8f7lYGU7-ilIlC_QL6WXWvGgEqGrQ',
    appId: '1:696594231265:web:5cf198c80b3e5d5d46eca0',
    messagingSenderId: '696594231265',
    projectId: 'leakdetectionapp',
    authDomain: 'leakdetectionapp.firebaseapp.com',
    storageBucket: 'leakdetectionapp.firebasestorage.app',
  );
}
